'use client';

import React, { createContext, useContext, useState, useCallback } from 'react';

type Language = 'fr' | 'en' | 'ar';

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    'nav.home': 'Accueil',
    'nav.about': 'Ait Ibouzryane',
    'nav.accommodations': 'Hébergements',
    'nav.experiences': 'Expériences',
    'nav.services': 'Services',
    'nav.gallery': 'Galerie',
    'nav.azilal': 'Azilal',
    'nav.contact': 'Contact',
    'nav.book': 'Réserver',
    'nav.whatsapp': 'WhatsApp',
    'hero.title': 'Bienvenue à Ait Ibouzryane',
    'hero.subtitle': 'Une expérience authentique au cœur de la nature d\'Azilal',
    'hero.desc': 'Maison d\'hôtes au cœur de la province d\'Azilal, entourée de montagnes, de jardins et de l\'hospitalité marocaine la plus sincère.',
    'hero.discover': 'Découvrir',
    'hero.book': 'Réserver',
    'hero.contact': 'Nous contacter',
    'intro.label': 'Notre maison',
    'intro.title': 'Une parenthèse authentique à Azilal',
    'intro.desc': 'Nichée dans le douar Iskoutane, à Timoulilte, la maison d\'hôtes Ait Ibouzryane vous accueille dans un cadre naturel d\'une beauté rare. Entre jardins fleuris, terrasses ensoleillées et vues sur les montagnes, chaque séjour devient une expérience mémorable.',
    'intro.more': 'En savoir plus',
    'rooms.label': 'Hébergements',
    'rooms.title': 'Vos espaces de repos',
    'rooms.subtitle': 'Chambres et suites conçues pour le confort et l\'authenticité',
    'rooms.view': 'Découvrir',
    'rooms.book': 'Réserver',
    'exp.label': 'Expériences',
    'exp.title': 'Vivez la région',
    'exp.subtitle': 'Randonnées, culture et nature au cœur d\'Azilal',
    'exp.discover': 'Découvrir',
    'reviews.label': 'Avis',
    'reviews.title': 'L\'expérience de nos visiteurs',
    'reviews.source': 'Avis vérifiés',
    'dest.label': 'Destination',
    'dest.title': 'Azilal, une région à découvrir',
    'dest.desc': 'La province d\'Azilal vous réserve des paysages grandioses, des villages authentiques et une culture millénaire. Partez à la découverte de ce territoire préservé.',
    'dest.explore': 'Explorer la région',
    'footer.tagline': 'Timoulilte — Azilal, Maroc',
    'footer.address': 'Douar Iskoutane, Timoulilte\nProvince d\'Azilal, Maroc',
    'footer.phone': '+212 662 681 618',
    'footer.legal': 'Mentions légales',
    'footer.privacy': 'Confidentialité',
    'footer.booking': 'Réservation',
    'footer.copyright': '© 2026 Ait Ibouzryane. Tous droits réservés.',
    'footer.license': 'Licence: 22000MH1651',
    'book.title': 'Demande de Réservation',
    'book.arrival': 'Date d\'arrivée',
    'book.departure': 'Date de départ',
    'book.adults': 'Adultes',
    'book.children': 'Enfants',
    'book.room': 'Chambre souhaitée',
    'book.name': 'Nom complet',
    'book.phone': 'Téléphone',
    'book.email': 'Email',
    'book.message': 'Message',
    'book.submit': 'Envoyer la demande',
    'book.check': 'Vérifier la disponibilité',
    'contact.title': 'Nous contacter',
    'contact.address': 'Adresse',
    'contact.phone': 'Téléphone',
    'contact.email': 'Email',
    'contact.form': 'Formulaire de contact',
    'contact.send': 'Envoyer',
    'contact.subject': 'Sujet',
    'contact.guests': 'Nombre de personnes',
    'gallery.title': 'Galerie',
    'gallery.label': 'Visuel',
    'gallery.all': 'Tout',
    'gallery.property': 'Ait Ibouzryane',
    'gallery.rooms': 'Hébergements',
    'gallery.nature': 'Nature',
    'gallery.mountains': 'Montagnes',
    'gallery.gastro': 'Gastronomie',
    'gallery.experiences': 'Expériences',
    'about.label': 'Notre histoire',
    'about.title': 'Ait Ibouzryane',
    'about.subtitle': 'Une maison, une famille, une région',
    'about.desc1': 'Bienvenue à Ait Ibouzryane, maison d\'hôtes authentique située dans le douar Iskoutane, au cœur de la commune de Timoulilte, province d\'Azilal. Notre établissement vous propose un cadre naturel exceptionnel, entre jardins, terrasses et vues sur les montagnes de l\'Atlas.',
    'about.desc2': 'Notée 9.2/10 sur bedandbreakfast.eu avec 268 avis, notre maison est reconnue pour son accueil chaleureux, sa cuisine du terroir et ses espaces de détente. Chaque visiteur repart avec des souvenirs inoubliables de la région d\'Azilal.',
    'about.amenities': 'Équipements & Services',
    'about.license': 'Licence d\'établissement',
    'acc.label': 'Nos chambres',
    'acc.title': 'Hébergements',
    'acc.subtitle': 'Chaque espace pensé pour votre confort',
    'acc.sqm': 'm²',
    'acc.capacity': 'Capacité',
    'acc.bed': 'Lit',
    'acc.bathroom': 'Salle de bain',
    'acc.terrace': 'Terrasse privée',
    'acc.ac': 'Climatisation',
    'acc.view': 'Vue',
    'acc.request': 'Demander une réservation',
    'exp.page.label': 'Activités',
    'exp.page.title': 'Expériences & Activités',
    'exp.page.subtitle': 'Découvrez la richesse naturelle et culturelle d\'Azilal',
    'exp.page.duration': 'Durée',
    'exp.page.difficulty': 'Difficulté',
    'exp.page.inquire': 'Renseignements',
    'success.form': 'Votre message a été envoyé. Nous vous répondrons dans les plus brefs délais.',
  },
  en: {
    'nav.home': 'Home',
    'nav.about': 'Ait Ibouzryane',
    'nav.accommodations': 'Accommodations',
    'nav.experiences': 'Experiences',
    'nav.services': 'Services',
    'nav.gallery': 'Gallery',
    'nav.azilal': 'Azilal',
    'nav.contact': 'Contact',
    'nav.book': 'Book',
    'nav.whatsapp': 'WhatsApp',
    'hero.title': 'Welcome to Ait Ibouzryane',
    'hero.subtitle': 'An authentic experience in the heart of Azilal\'s nature',
    'hero.desc': 'A guesthouse in the heart of Azilal province, surrounded by mountains, gardens and the most sincere Moroccan hospitality.',
    'hero.discover': 'Discover',
    'hero.book': 'Book',
    'hero.contact': 'Contact us',
    'intro.label': 'Our home',
    'intro.title': 'An authentic retreat in Azilal',
    'intro.desc': 'Nestled in the douar of Iskoutane, in Timoulilte, Ait Ibouzryane welcomes you in a natural setting of rare beauty. Between flowering gardens, sunny terraces and mountain views, every stay becomes a memorable experience.',
    'intro.more': 'Learn more',
    'rooms.label': 'Accommodations',
    'rooms.title': 'Your spaces to rest',
    'rooms.subtitle': 'Rooms and suites designed for comfort and authenticity',
    'rooms.view': 'Discover',
    'rooms.book': 'Book',
    'exp.label': 'Experiences',
    'exp.title': 'Live the region',
    'exp.subtitle': 'Hiking, culture and nature in the heart of Azilal',
    'exp.discover': 'Discover',
    'reviews.label': 'Reviews',
    'reviews.title': 'Our visitors\' experience',
    'reviews.source': 'Verified reviews',
    'dest.label': 'Destination',
    'dest.title': 'Azilal, a region to discover',
    'dest.desc': 'The province of Azilal offers breathtaking landscapes, authentic villages and a millennia-old culture. Discover this preserved territory.',
    'dest.explore': 'Explore the region',
    'footer.tagline': 'Timoulilte — Azilal, Morocco',
    'footer.address': 'Douar Iskoutane, Timoulilte\nAzilal Province, Morocco',
    'footer.phone': '+212 662 681 618',
    'footer.legal': 'Legal Notice',
    'footer.privacy': 'Privacy',
    'footer.booking': 'Booking',
    'footer.copyright': '© 2026 Ait Ibouzryane. All rights reserved.',
    'footer.license': 'License: 22000MH1651',
    'book.title': 'Reservation Request',
    'book.arrival': 'Arrival date',
    'book.departure': 'Departure date',
    'book.adults': 'Adults',
    'book.children': 'Children',
    'book.room': 'Desired room',
    'book.name': 'Full name',
    'book.phone': 'Phone',
    'book.email': 'Email',
    'book.message': 'Message',
    'book.submit': 'Send request',
    'book.check': 'Check availability',
    'contact.title': 'Contact us',
    'contact.address': 'Address',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.form': 'Contact form',
    'contact.send': 'Send',
    'contact.subject': 'Subject',
    'contact.guests': 'Number of guests',
    'gallery.title': 'Gallery',
    'gallery.label': 'Visual',
    'gallery.all': 'All',
    'gallery.property': 'Ait Ibouzryane',
    'gallery.rooms': 'Accommodations',
    'gallery.nature': 'Nature',
    'gallery.mountains': 'Mountains',
    'gallery.gastro': 'Gastronomy',
    'gallery.experiences': 'Experiences',
    'about.label': 'Our story',
    'about.title': 'Ait Ibouzryane',
    'about.subtitle': 'A home, a family, a region',
    'about.desc1': 'Welcome to Ait Ibouzryane, an authentic guesthouse located in the douar of Iskoutane, in the heart of the commune of Timoulilte, Azilal province. Our establishment offers you an exceptional natural setting, between gardens, terraces and views of the Atlas mountains.',
    'about.desc2': 'Rated 9.2/10 on bedandbreakfast.eu with 268 reviews, our home is recognized for its warm welcome, local cuisine and relaxation spaces. Every visitor leaves with unforgettable memories of the Azilal region.',
    'about.amenities': 'Amenities & Services',
    'about.license': 'Establishment License',
    'acc.label': 'Our rooms',
    'acc.title': 'Accommodations',
    'acc.subtitle': 'Every space designed for your comfort',
    'acc.sqm': 'm²',
    'acc.capacity': 'Capacity',
    'acc.bed': 'Bed',
    'acc.bathroom': 'Bathroom',
    'acc.terrace': 'Private terrace',
    'acc.ac': 'Air conditioning',
    'acc.view': 'View',
    'acc.request': 'Request a booking',
    'exp.page.label': 'Activities',
    'exp.page.title': 'Experiences & Activities',
    'exp.page.subtitle': 'Discover the natural and cultural richness of Azilal',
    'exp.page.duration': 'Duration',
    'exp.page.difficulty': 'Difficulty',
    'exp.page.inquire': 'Inquire',
    'success.form': 'Your message has been sent. We will reply as soon as possible.',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.about': 'آيت إبوزريان',
    'nav.accommodations': 'الإقامة',
    'nav.experiences': 'التجارب',
    'nav.services': 'الخدمات',
    'nav.gallery': 'المعرض',
    'nav.azilal': 'أزيلال',
    'nav.contact': 'اتصل بنا',
    'nav.book': 'احجز',
    'nav.whatsapp': 'واتساب',
    'hero.title': 'أهلاً بكم في آيت إبوزريان',
    'hero.subtitle': 'تجربة أصيلة في قلب طبيعة أزيلال',
    'hero.desc': 'بيت ضيافة في قلب إقليم أزيلال، محاط بالجبال والحدائق وأصدق مظاهر الضيافة المغربية.',
    'hero.discover': 'اكتشف',
    'hero.book': 'احجز',
    'hero.contact': 'اتصل بنا',
    'intro.label': 'بيتنا',
    'intro.title': 'استراحة أصيلة في أزيلال',
    'intro.desc': 'يقع بيت الضيافة آيت إبوزريان في دوار إسكوتان بتيمولتيت، ويرحب بكم في إطار طبيعي نادر الجمال. بين الحدائق المزهرة والمدرجات المشمسة والمناظر الجبلية، تصبح كل زيارة تجربة لا تُنسى.',
    'intro.more': 'اعرف المزيد',
    'rooms.label': 'الإقامة',
    'rooms.title': 'أماكن الراحة الخاصة بكم',
    'rooms.subtitle': 'غرف وأجنحة مصممة للراحة والأصالة',
    'rooms.view': 'اكتشف',
    'rooms.book': 'احجز',
    'exp.label': 'التجارب',
    'exp.title': 'عيش المنطقة',
    'exp.subtitle': 'المشي والثقافة والطبيعة في قلب أزيلال',
    'exp.discover': 'اكتشف',
    'reviews.label': 'التقييمات',
    'reviews.title': 'تجربة زوارنا',
    'reviews.source': 'تقييمات موثقة',
    'dest.label': 'الوجهة',
    'dest.title': 'أزيلال، منطقة تستحق الاكتشاف',
    'dest.desc': 'تقدم إقليم أزيلال مناظر خلابة وقرى أصيلة وثقافة ضاربة في التاريخ. اكتشف هذه المنطقة المحمية.',
    'dest.explore': 'استكشف المنطقة',
    'footer.tagline': 'تيمولتيت — أزيلال، المغرب',
    'footer.address': 'دوار إسكوتان، تيمولتيت\nإقليم أزيلال، المغرب',
    'footer.phone': '618 681 662 212+',
    'footer.legal': 'الإشعارات القانونية',
    'footer.privacy': 'الخصوصية',
    'footer.booking': 'الحجز',
    'footer.copyright': '© 2026 آيت إبوزريان. جميع الحقوق محفوظة.',
    'footer.license': 'الرخصة: 22000MH1651',
    'book.title': 'طلب حجز',
    'book.arrival': 'تاريخ الوصول',
    'book.departure': 'تاريخ المغادرة',
    'book.adults': 'البالغون',
    'book.children': 'الأطفال',
    'book.room': 'الغرفة المطلوبة',
    'book.name': 'الاسم الكامل',
    'book.phone': 'الهاتف',
    'book.email': 'البريد الإلكتروني',
    'book.message': 'رسالة',
    'book.submit': 'إرسال الطلب',
    'book.check': 'تحقق من التوفر',
    'contact.title': 'اتصل بنا',
    'contact.address': 'العنوان',
    'contact.phone': 'الهاتف',
    'contact.email': 'البريد الإلكتروني',
    'contact.form': 'نموذج الاتصال',
    'contact.send': 'إرسال',
    'contact.subject': 'الموضوع',
    'contact.guests': 'عدد الأشخاص',
    'gallery.title': 'المعرض',
    'gallery.label': 'الصور',
    'gallery.all': 'الكل',
    'gallery.property': 'آيت إبوزريان',
    'gallery.rooms': 'الإقامة',
    'gallery.nature': 'الطبيعة',
    'gallery.mountains': 'الجبال',
    'gallery.gastro': 'المطبخ',
    'gallery.experiences': 'التجارب',
    'about.label': 'قصتنا',
    'about.title': 'آيت إبوزريان',
    'about.subtitle': 'بيت، عائلة، منطقة',
    'about.desc1': 'مرحباً بكم في آيت إبوزريان، بيت ضيافة أصيل يقع في دوار إسكوتان، في قلب جماعة تيمولتيت، إقليم أزيلال. يقدم مؤسستنا إطاراً طبيعياً استثنائياً بين الحدائق والمدرجات والمناظر الجبلية.',
    'about.desc2': 'حصل على تقييم 9.2/10 على bedandbreakfast.eu مع 268 تقييماً، بيتنا معروف بحفاوة الاستقبال والمطبخ المحلي وفضاءات الاسترخاء.',
    'about.amenities': 'المرافق والخدمات',
    'about.license': 'رخصة المؤسسة',
    'acc.label': 'غرفنا',
    'acc.title': 'الإقامة',
    'acc.subtitle': 'كل فضاء مصمم لراحتكم',
    'acc.sqm': 'م²',
    'acc.capacity': 'السعة',
    'acc.bed': 'السرير',
    'acc.bathroom': 'الحمام',
    'acc.terrace': 'تراس خاص',
    'acc.ac': 'تكييف الهواء',
    'acc.view': 'الإطلالة',
    'acc.request': 'طلب حجز',
    'exp.page.label': 'الأنشطة',
    'exp.page.title': 'التجارب والأنشطة',
    'exp.page.subtitle': 'اكتشف الثروة الطبيعية والثقافية لأزيلال',
    'exp.page.duration': 'المدة',
    'exp.page.difficulty': 'الصعوبة',
    'exp.page.inquire': 'استفسار',
    'success.form': 'تم إرسال رسالتك. سنرد عليك في أقرب وقت ممكن.',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: 'fr',
  setLang: () => {},
  t: (k) => k,
  dir: 'ltr',
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>('fr');

  const setLang = useCallback((l: Language) => {
    setLangState(l);
    if (typeof document !== 'undefined') {
      document.documentElement.lang = l;
      document.documentElement.dir = l === 'ar' ? 'rtl' : 'ltr';
    }
  }, []);

  const t = useCallback((key: string): string => {
    return translations[lang][key] || translations['fr'][key] || key;
  }, [lang]);

  const dir = lang === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      <div dir={dir}>{children}</div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}